module.exports = require('./lib/twss');
console.log("hello")
console.log(module.exports.prob("Choke me, I dare you"))
console.log(module.exports.prob("It's too tight I need to pull out"))
console.log(module.exports.prob("this is hard"))
console.log(module.exports.prob("don't stick that in me"))
console.log(module.exports.prob("this is hard"))
console.log(module.exports.prob("Wow"))
console.log(module.exports.prob("This weather is good"))
console.log(module.exports.prob("There it is"))
console.log(module.exports.prob("the cofa is a shield surmounted by a seven branched candelabra which incorporates the star of zion. The shield is parted per saltier and within the shield appear the following symbols. In chief a lion rampant turned toward dexter margin. on dexter flank, the flour de lis. on sinister flank a lamp of knowledge. At the base an open book upon the pages of which there rests a human skull and the fraternity pledge pin. Below the shield there is a scroll on which appear the following greek letters."))