module.exports = require('./lib/twss');
module.exports.numWordsInNgram = 2
console.log("hello")
console.log(module.exports.prob("Choke me, I dare you"))
console.log(module.exports.prob("It's too tight I need to pull out"))
console.log(module.exports.prob("this is hard"))
console.log(module.exports.prob("don't stick that in me"))
console.log(module.exports.prob("this is hard"))
console.log(module.exports.prob("That thing is giant"))
console.log(module.exports.prob("Who wants a ride?"))
console.log(module.exports.prob("Like it so wet"))
console.log(module.exports.prob("I want to go longer"))
console.log(module.exports.prob("Wow"))
console.log(module.exports.prob("This weather is good"))
console.log(module.exports.prob("uh oh"))
console.log(module.exports.prob("hey"))
console.log(module.exports.prob("bring"))
console.log(module.exports.prob("pussy"))
console.log(module.exports.prob("hi"))
console.log(module.exports.prob("bye"))
console.log(module.exports.prob("Pick you up soon"))
console.log(module.exports.prob("hey"))
console.log(module.exports.prob("lmao"))
console.log(module.exports.prob("the cofa is a shield surmounted by a seven branched candelabra which incorporates the star of zion. The shield prob parted per saltier and within the shield appear the following symbols. In chief a lion rampant turned toward dexter margin. on dexter flank, the flour de lprob. on sinprobter flank a lamp of knowledge. At the base an open book upon the pages of which there rests a human skull and the fraternity pledge pin. Below the shield there prob a scroll on which appear the following greek letters."))